CREATE USER IF NOT EXISTS 'mdso'@'localhost' IDENTIFIED BY "mdso1234";
GRANT ALL PRIVILEGES ON *.* TO 'mdso'@'localhost';
FLUSH PRIVILEGES;
CREATE DATABASE IF NOT EXISTS mdso;

USE mdso;

CREATE TABLE IF NOT EXISTS mdsoMember (
	id TINYINT(20) PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100),
	lastName VARCHAR(100),
	mail VARCHAR(100),
	status VARCHAR(100),
	UNIQUE(id)
);
