name: app-front

on:
        workflow_dispatch:
                inputs:
                        version:
                                description: "app de front"
                                required: false
                                type: string
                                default: "1.0.0"

jobs:
        security:
                runs-on: ubunut-latest

                steps:
                        - uses: actions/checkout@v2
                        - name: Run Gitleaks
                          uses: eeveebank/github-actions-gitleaks@v1.0.0
                          with:
                                  depth: 1
        contenair-buid:
                needs: security
                runs-on: ubuntu-latest

                steps:
                        - name: Set up Docker
                          uses: docker/setup-buildx-action@v1
                        - name: Login to DockerHub
                          uses: docker/login-action@v1
                          with:
                                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                                  password: ${{ secrets.DOCKERHUB_TOKEN }}
                        - name: Build and push
                          uses: docker/build-push-action@v2
                          with:
                                  push: true
                                  tags: startlingadama/anima-login:v1
